students = open("students_statistics.txt", "+w")

students.write("Students of Class 8\n")
students.write("NAME      PERFORMACE\n")
students.write("Adib          A\n")
students.write("Sadman        A\n") 
students.write("Aqib          A-\n")
students.write("Raju          A+\n") 
students.write("Jahid         B-\n")
students.write("Arafat        F\n") 
students.write("Safwan        D\n")
students.write("Safarat       A+")
# students.write("\n") 
print("File 'students_statistics.txt' has been created and written to successfully.")
print(students.read())
print(students.readlines())
